# Generated by Django 3.0.5 on 2020-04-12 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('slug', models.SlugField(unique=True)),
                ('draft', models.BooleanField(default=True)),
                ('manufacture', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('star_rating', models.CharField(max_length=120)),
                ('price', models.CharField(max_length=120)),
                ('sale_price', models.CharField(max_length=120)),
                ('shipping', models.CharField(max_length=120)),
                ('inventory', models.CharField(max_length=120)),
                ('features', models.TextField()),
                ('description', models.TextField()),
                ('dimensions', models.CharField(max_length=120)),
                ('item_weight', models.CharField(max_length=120)),
                ('shipping_weight', models.CharField(max_length=120)),
                ('ASIN', models.CharField(max_length=120)),
                ('model_number', models.CharField(max_length=120)),
                ('batteries', models.CharField(max_length=120)),
                ('review_blip', models.CharField(max_length=120)),
                ('BSR', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
