# Generated by Django 3.0.5 on 2020-04-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
    ]
